#############################################################################
# Makefile for building: MonitorWind
# Generated by qmake (2.01a) (Qt 4.5.0) on: ?? 5? 20 18:44:01 2011
# Project:  MonitorWind.pro
# Template: app
# Command: /home/zhigang/at91sam/arm-qt4/bin/Qmake -unix -o Makefile MonitorWind.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../at91sam/arm-qt4/mkspecs/default -I. -I../../at91sam/arm-qt4/include/QtCore -I../../at91sam/arm-qt4/include/QtNetwork -I../../at91sam/arm-qt4/include/QtGui -I../../at91sam/arm-qt4/include -I. -I. -I.
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/zhigang/at91sam/arm-qt4/lib
LIBS          = $(SUBLIBS)  -L/home/zhigang/at91sam/arm-qt4//lib -lQtGui -L/home/zhigang/at91sam/tslib/lib -L/home/zhigang/at91sam/arm-qt4//lib -lts -lQtNetwork -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /home/zhigang/at91sam/arm-qt4/bin/Qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = DataTransferThread\ .cpp \
		GroupContainer.cpp \
		main.cpp \
		MonitorThread.cpp \
		MonitorWind.cpp \
		SetupWindow.cpp \
		WaveShow.cpp moc_DataTransferThread.cpp \
		moc_GroupContainer.cpp \
		moc_MonitorThread.cpp \
		moc_MonitorWind.cpp \
		moc_SetupWindow.cpp \
		moc_WaveShow.cpp \
		qrc_MonitorWind.cpp
OBJECTS       = DataTransferThread\ .o \
		GroupContainer.o \
		main.o \
		MonitorThread.o \
		MonitorWind.o \
		SetupWindow.o \
		WaveShow.o \
		moc_DataTransferThread.o \
		moc_GroupContainer.o \
		moc_MonitorThread.o \
		moc_MonitorWind.o \
		moc_SetupWindow.o \
		moc_WaveShow.o \
		qrc_MonitorWind.o
DIST          = ../../at91sam/arm-qt4/mkspecs/common/g++.conf \
		../../at91sam/arm-qt4/mkspecs/common/unix.conf \
		../../at91sam/arm-qt4/mkspecs/common/linux.conf \
		../../at91sam/arm-qt4/mkspecs/common/qws.conf \
		../../at91sam/arm-qt4/mkspecs/qconfig.pri \
		../../at91sam/arm-qt4/mkspecs/features/qt_functions.prf \
		../../at91sam/arm-qt4/mkspecs/features/qt_config.prf \
		../../at91sam/arm-qt4/mkspecs/features/exclusive_builds.prf \
		../../at91sam/arm-qt4/mkspecs/features/default_pre.prf \
		../../at91sam/arm-qt4/mkspecs/features/release.prf \
		../../at91sam/arm-qt4/mkspecs/features/default_post.prf \
		../../at91sam/arm-qt4/mkspecs/features/warn_on.prf \
		../../at91sam/arm-qt4/mkspecs/features/qt.prf \
		../../at91sam/arm-qt4/mkspecs/features/unix/thread.prf \
		../../at91sam/arm-qt4/mkspecs/features/moc.prf \
		../../at91sam/arm-qt4/mkspecs/features/resources.prf \
		../../at91sam/arm-qt4/mkspecs/features/uic.prf \
		../../at91sam/arm-qt4/mkspecs/features/yacc.prf \
		../../at91sam/arm-qt4/mkspecs/features/lex.prf \
		MonitorWind.pro
QMAKE_TARGET  = MonitorWind
DESTDIR       = 
TARGET        = MonitorWind

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MonitorWind.pro  ../../at91sam/arm-qt4/mkspecs/default/qmake.conf ../../at91sam/arm-qt4/mkspecs/common/g++.conf \
		../../at91sam/arm-qt4/mkspecs/common/unix.conf \
		../../at91sam/arm-qt4/mkspecs/common/linux.conf \
		../../at91sam/arm-qt4/mkspecs/common/qws.conf \
		../../at91sam/arm-qt4/mkspecs/qconfig.pri \
		../../at91sam/arm-qt4/mkspecs/features/qt_functions.prf \
		../../at91sam/arm-qt4/mkspecs/features/qt_config.prf \
		../../at91sam/arm-qt4/mkspecs/features/exclusive_builds.prf \
		../../at91sam/arm-qt4/mkspecs/features/default_pre.prf \
		../../at91sam/arm-qt4/mkspecs/features/release.prf \
		../../at91sam/arm-qt4/mkspecs/features/default_post.prf \
		../../at91sam/arm-qt4/mkspecs/features/warn_on.prf \
		../../at91sam/arm-qt4/mkspecs/features/qt.prf \
		../../at91sam/arm-qt4/mkspecs/features/unix/thread.prf \
		../../at91sam/arm-qt4/mkspecs/features/moc.prf \
		../../at91sam/arm-qt4/mkspecs/features/resources.prf \
		../../at91sam/arm-qt4/mkspecs/features/uic.prf \
		../../at91sam/arm-qt4/mkspecs/features/yacc.prf \
		../../at91sam/arm-qt4/mkspecs/features/lex.prf \
		/home/zhigang/at91sam/arm-qt4/lib/libQtGui.prl \
		/home/zhigang/at91sam/arm-qt4/lib/libQtNetwork.prl \
		/home/zhigang/at91sam/arm-qt4/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile MonitorWind.pro
../../at91sam/arm-qt4/mkspecs/common/g++.conf:
../../at91sam/arm-qt4/mkspecs/common/unix.conf:
../../at91sam/arm-qt4/mkspecs/common/linux.conf:
../../at91sam/arm-qt4/mkspecs/common/qws.conf:
../../at91sam/arm-qt4/mkspecs/qconfig.pri:
../../at91sam/arm-qt4/mkspecs/features/qt_functions.prf:
../../at91sam/arm-qt4/mkspecs/features/qt_config.prf:
../../at91sam/arm-qt4/mkspecs/features/exclusive_builds.prf:
../../at91sam/arm-qt4/mkspecs/features/default_pre.prf:
../../at91sam/arm-qt4/mkspecs/features/release.prf:
../../at91sam/arm-qt4/mkspecs/features/default_post.prf:
../../at91sam/arm-qt4/mkspecs/features/warn_on.prf:
../../at91sam/arm-qt4/mkspecs/features/qt.prf:
../../at91sam/arm-qt4/mkspecs/features/unix/thread.prf:
../../at91sam/arm-qt4/mkspecs/features/moc.prf:
../../at91sam/arm-qt4/mkspecs/features/resources.prf:
../../at91sam/arm-qt4/mkspecs/features/uic.prf:
../../at91sam/arm-qt4/mkspecs/features/yacc.prf:
../../at91sam/arm-qt4/mkspecs/features/lex.prf:
/home/zhigang/at91sam/arm-qt4/lib/libQtGui.prl:
/home/zhigang/at91sam/arm-qt4/lib/libQtNetwork.prl:
/home/zhigang/at91sam/arm-qt4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile MonitorWind.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MonitorWind1.0.0 || $(MKDIR) .tmp/MonitorWind1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MonitorWind1.0.0/ && $(COPY_FILE) --parents DataTransferThread.h GroupContainer.h MonitorThread.h MonitorWind.h SetupWindow.h WaveShow.h .tmp/MonitorWind1.0.0/ && $(COPY_FILE) --parents MonitorWind.qrc .tmp/MonitorWind1.0.0/ && $(COPY_FILE) --parents DataTransferThread .cpp GroupContainer.cpp main.cpp MonitorThread.cpp MonitorWind.cpp SetupWindow.cpp WaveShow.cpp .tmp/MonitorWind1.0.0/ && (cd `dirname .tmp/MonitorWind1.0.0` && $(TAR) MonitorWind1.0.0.tar MonitorWind1.0.0 && $(COMPRESS) MonitorWind1.0.0.tar) && $(MOVE) `dirname .tmp/MonitorWind1.0.0`/MonitorWind1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MonitorWind1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_DataTransferThread.cpp moc_GroupContainer.cpp moc_MonitorThread.cpp moc_MonitorWind.cpp moc_SetupWindow.cpp moc_WaveShow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DataTransferThread.cpp moc_GroupContainer.cpp moc_MonitorThread.cpp moc_MonitorWind.cpp moc_SetupWindow.cpp moc_WaveShow.cpp
moc_DataTransferThread.cpp: DataTransferThread.h
	/home/zhigang/at91sam/arm-qt4//bin/moc $(DEFINES) $(INCPATH) DataTransferThread.h -o moc_DataTransferThread.cpp

moc_GroupContainer.cpp: GroupContainer.h
	/home/zhigang/at91sam/arm-qt4//bin/moc $(DEFINES) $(INCPATH) GroupContainer.h -o moc_GroupContainer.cpp

moc_MonitorThread.cpp: MonitorThread.h
	/home/zhigang/at91sam/arm-qt4//bin/moc $(DEFINES) $(INCPATH) MonitorThread.h -o moc_MonitorThread.cpp

moc_MonitorWind.cpp: WaveShow.h \
		GroupContainer.h \
		MonitorThread.h \
		DataTransferThread.h \
		SetupWindow.h \
		MonitorWind.h \
		MonitorWind.h
	/home/zhigang/at91sam/arm-qt4//bin/moc $(DEFINES) $(INCPATH) MonitorWind.h -o moc_MonitorWind.cpp

moc_SetupWindow.cpp: MonitorWind.h \
		WaveShow.h \
		GroupContainer.h \
		MonitorThread.h \
		DataTransferThread.h \
		SetupWindow.h \
		SetupWindow.h
	/home/zhigang/at91sam/arm-qt4//bin/moc $(DEFINES) $(INCPATH) SetupWindow.h -o moc_SetupWindow.cpp

moc_WaveShow.cpp: WaveShow.h
	/home/zhigang/at91sam/arm-qt4//bin/moc $(DEFINES) $(INCPATH) WaveShow.h -o moc_WaveShow.cpp

compiler_rcc_make_all: qrc_MonitorWind.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_MonitorWind.cpp
qrc_MonitorWind.cpp: MonitorWind.qrc \
		images/xinzang.png \
		images/fei.png
	/home/zhigang/at91sam/arm-qt4/bin/rcc -name MonitorWind MonitorWind.qrc -o qrc_MonitorWind.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

DataTransferThread\ .o: DataTransferThread\ .cpp DataTransferThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataTransferThread\ .o DataTransferThread\ .cpp

GroupContainer.o: GroupContainer.cpp GroupContainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GroupContainer.o GroupContainer.cpp

main.o: main.cpp MonitorWind.h \
		WaveShow.h \
		GroupContainer.h \
		MonitorThread.h \
		DataTransferThread.h \
		SetupWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MonitorThread.o: MonitorThread.cpp MonitorThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MonitorThread.o MonitorThread.cpp

MonitorWind.o: MonitorWind.cpp MonitorWind.h \
		WaveShow.h \
		GroupContainer.h \
		MonitorThread.h \
		DataTransferThread.h \
		SetupWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MonitorWind.o MonitorWind.cpp

SetupWindow.o: SetupWindow.cpp SetupWindow.h \
		MonitorWind.h \
		WaveShow.h \
		GroupContainer.h \
		MonitorThread.h \
		DataTransferThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SetupWindow.o SetupWindow.cpp

WaveShow.o: WaveShow.cpp WaveShow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaveShow.o WaveShow.cpp

moc_DataTransferThread.o: moc_DataTransferThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DataTransferThread.o moc_DataTransferThread.cpp

moc_GroupContainer.o: moc_GroupContainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GroupContainer.o moc_GroupContainer.cpp

moc_MonitorThread.o: moc_MonitorThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MonitorThread.o moc_MonitorThread.cpp

moc_MonitorWind.o: moc_MonitorWind.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MonitorWind.o moc_MonitorWind.cpp

moc_SetupWindow.o: moc_SetupWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SetupWindow.o moc_SetupWindow.cpp

moc_WaveShow.o: moc_WaveShow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WaveShow.o moc_WaveShow.cpp

qrc_MonitorWind.o: qrc_MonitorWind.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_MonitorWind.o qrc_MonitorWind.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

